




.build/mega2560/src/client.cpp : src/client.ino
	@mkdir -p .build/mega2560/src
	@echo [93msrc/client.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/mega2560/src/client.cpp
	@true

